production:
  adapter: postgresql
  encoding: unicode
  database: pandera_development
  pool: 5
  username: lotbud
  password: password1

development:
  adapter: postgresql
  encoding: unicode
  database: pandera_development
  pool: 5
  username: lotbud
  password: password1
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: pandera_test
  pool: 5
  username: lotbud
  password: password1
