# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da2665c33036da5d2cce11f7b83d41e6e873894adf92c25f11848e0d75878f88153caa111776dc65f62348b9e79a1ce7144ed5d65b467f1f24d8ffdf6ca7cd17

test:
  secret_key_base: 0a3258aadd9f531b1d89c794910f82dcd29038c9e5826c999b4ebbccc1763732e9b6ab691ce88ec9fd5f80c3abb2c25667dc9560aa4b09e829a6f99c28d72e0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
